export const load = [
  {
    'id': '1',
    'name': 'Аналіз вимог до програмного забезпечення (ЗФН)',
    'sem': '1',
    'firstGroup': '1',
    'firstStudents': '19',
    'secondGroup': '',
    'secondStudents': '',
    'lecture': '15',
    'sessions': '',
    'lab': '50',
    'consultations': '',
    'projectAssessment': '',
    'homework': '31',
    'coursework': '6',
    'guidance': '',
    'exams': '',
    'practiceGuidance': '',
    'industrialSupervision': '',
    'reportDefense': '',
    'qualProjectSupervision': '',
    'qualWorkConsultation': '',
    'finalAssessment': '',
    'postgradExams': '',
    'postgradSupervision': '',
    'doctoralMentoring': '',
    'otherTasks': '22'
  },
  {
    'id': '2',
    'name': 'Аналіз вимог до програмного забезпечення (ФККПІ)',
    'sem': '1',
    'firstGroup': '6',
    'firstStudents': '180',
    'secondGroup': '',
    'secondStudents': '',
    'lecture': '20',
    'sessions': '',
    'lab': '60',
    'consultations': '4',
    'projectAssessment': '',
    'homework': '2',
    'coursework': '',
    'guidance': '',
    'exams': '',
    'practiceGuidance': '',
    'industrialSupervision': '',
    'reportDefense': '',
    'qualProjectSupervision': '',
    'qualWorkConsultation': '',
    'finalAssessment': '',
    'postgradExams': '',
    'postgradSupervision': '',
    'doctoralMentoring': '',
    'otherTasks': '25'
  },
  {
    'id': '3',
    'name': 'Бази даних (ФККПІ)',
    'sem': '1',
    'firstGroup': '9',
    'firstStudents': '260',
    'secondGroup': '',
    'secondStudents': '',
    'lecture': '25',
    'sessions': '',
    'lab': '40',
    'consultations': '',
    'projectAssessment': '',
    'homework': '7',
    'coursework': '',
    'guidance': '',
    'exams': '',
    'practiceGuidance': '',
    'industrialSupervision': '2',
    'reportDefense': '',
    'qualProjectSupervision': '',
    'qualWorkConsultation': '',
    'finalAssessment': '',
    'postgradExams': '',
    'postgradSupervision': '',
    'doctoralMentoring': '',
    'otherTasks': '30'
  },
  {
    'id': '4',
    'name': 'Переддипломна практика (ФККПІ)',
    'sem': '1',
    'firstGroup': '1',
    'firstStudents': '3',
    'secondGroup': '',
    'secondStudents': '',
    'lecture': '12',
    'sessions': '',
    'lab': '54',
    'consultations': '10',
    'projectAssessment': '',
    'homework': '',
    'coursework': '',
    'guidance': '',
    'exams': '',
    'practiceGuidance': '',
    'industrialSupervision': '4',
    'reportDefense': '',
    'qualProjectSupervision': '',
    'qualWorkConsultation': '',
    'finalAssessment': '',
    'postgradExams': '',
    'postgradSupervision': '',
    'doctoralMentoring': '',
    'otherTasks': '25'
  },
  {
    'id': '5',
    'name': 'Моделювання та аналіз програмного забезпечення (ФККПІ)',
    'sem': '2',
    'firstGroup': '',
    'firstStudents': '',
    'secondGroup': '9',
    'secondStudents': '260',
    'lecture': '4',
    'sessions': '',
    'lab': '4',
    'consultations': '6',
    'projectAssessment': '',
    'homework': '5',
    'coursework': '42',
    'guidance': '',
    'exams': '',
    'practiceGuidance': '',
    'industrialSupervision': '12',
    'reportDefense': '',
    'qualProjectSupervision': '',
    'qualWorkConsultation': '',
    'finalAssessment': '',
    'postgradExams': '',
    'postgradSupervision': '',
    'doctoralMentoring': '',
    'otherTasks': '10'
  },
  {
    'id': '6',
    'name': 'Аналіз вимог до програмного забезпечення (ФККПІ)',
    'sem': '2',
    'firstGroup': '',
    'firstStudents': '',
    'secondGroup': '1',
    'secondStudents': '19',
    'lecture': '',
    'sessions': '',
    'lab': '4',
    'consultations': '',
    'projectAssessment': '',
    'homework': '',
    'coursework': '18',
    'guidance': '',
    'exams': '',
    'practiceGuidance': '',
    'industrialSupervision': '8',
    'reportDefense': '',
    'qualProjectSupervision': '',
    'qualWorkConsultation': '',
    'finalAssessment': '',
    'postgradExams': '',
    'postgradSupervision': '',
    'doctoralMentoring': '',
    'otherTasks': '7'
  },
  {
    'id': '7',
    'name': 'Технологічна практика',
    'sem': '2',
    'firstGroup': '',
    'firstStudents': '',
    'secondGroup': '1',
    'secondStudents': '30',
    'lecture': '',
    'sessions': '',
    'lab': '',
    'consultations': '',
    'projectAssessment': '',
    'homework': '',
    'coursework': '',
    'guidance': '',
    'exams': '',
    'practiceGuidance': '',
    'industrialSupervision': '',
    'reportDefense': '',
    'qualProjectSupervision': '',
    'qualWorkConsultation': '',
    'finalAssessment': '',
    'postgradExams': '',
    'postgradSupervision': '',
    'doctoralMentoring': '',
    'otherTasks': '60'
  },
]